INSERT INTO FLIGHTS(ORIGIN, DESTINATION, DURATION) VALUES("New York", "London", 415);
INSERT INTO FLIGHTS(ORIGIN, DESTINATION, DURATION) VALUES("Shanghai", "Paris", 760);
INSERT INTO FLIGHTS(ORIGIN, DESTINATION, DURATION) VALUES("Istanbul", "Tokyo", 700);
INSERT INTO FLIGHTS(ORIGIN, DESTINATION, DURATION) VALUES("New York", "Paris", 435);
INSERT INTO FLIGHTS(ORIGIN, DESTINATION, DURATION) VALUES("Moscow", "Paris", 245);
INSERT INTO FLIGHTS(ORIGIN, DESTINATION, DURATION) VALUES("Lima", "New York", 455);
